from flask.ext.wtf import Form
from wtforms import TextField, validators

# both classes take a form (generated by user's POST and GET requests apparently)
# and attach a TextField to it.
# My guess is that both does something to the HTML
# a Form is obviously described by HTML, the textfield is added to the form dynamically. 
class EnterDBInfo(Form):
    dbNotes = TextField(label='Items to add to DB', description="db_enter", validators=[validators.required(), validators.Length(min=0, max=128, message=u'Enter 128 characters or less')])    

class RetrieveDBInfo(Form):
    numRetrieve = TextField(label='Number of DB Items to Get', description="db_get", validators=[validators.required(), validators.Regexp('^\d{1}$',message=u'Enter a number between 1 and 10')])
